version: "3"

services:
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always #if ever the container failed, it will restart automatically
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  wiress_be:
    container_name: wiress_be
    build: . #location of the Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: dev
      PORT: 9000
      MONGODB_URI: mongodb://mongo_db:27017/test
    depends_on: #needs to define the prerequisites
      - mongo_db

volumes:
  mongo_db: {}

